version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ../.:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: /bin/bash -c "./docker/initialize_mssql.sh & /opt/mssql/bin/sqlservr"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ITsC0mpl1cat3d"