
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tdd_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'local_sql'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  tdd_dbt:
      # Applies to all files under models/flight_data
      flight_data:
          materialized: view

seeds:
  tdd_dbt:
    01_joinok:
      01_ontime_data_joinok:
        enabled: true
        schema: 01_joinok
        database: dev
        alias: ontime_data
        full_refresh: true
        tags: 01_joinok
      01_carrier_code_joinok:
        enabled: true
        schema: 01_joinok
        database: dev
        alias: carrier_code
        full_refresh: true
        quote_columns: true
        tags: 01_joinok
      01_ontime_denorm_joinok_expected:
        enabled: true
        schema: 01_joinok
        full_refresh: true
        database: dev
        tags: 01_joinok
    02_joinunknown:
      02_ontime_data_joinunknown:
        enabled: true
        database: dev
        schema: 02_joinunknown
        alias: ontime_data
        full_refresh: true
        tags: 02_joinunknown
      02_carrier_code_joinunknown:
        enabled: true
        database: dev
        schema: 02_joinunknown
        alias: carrier_code
        full_refresh: true
        quote_columns: true
        tags: 02_joinunknown
      02_ontime_denorm_joinunknown_expected:
        enabled: true
        full_refresh: true
        database: dev
        schema: 02_joinunknown
        tags: 02_joinunknown
    03_joincombined:
      03_ontime_data_joincombined:
        enabled: true
        database: dev
        schema: 03_joincombined
        alias: ontime_data
        full_refresh: true
        tags: 03_joincombined
      03_carrier_code_joincombined:
        enabled: true
        database: dev
        schema: 03_joincombined
        alias: carrier_code
        full_refresh: true
        quote_columns: true
        tags: 03_joincombined
      03_ontime_denorm_joincombined_expected:
        enabled: true
        full_refresh: true
        database: dev
        schema: 03_joincombined
        tags: 03_joincombined
